/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;


import javax.swing.JFrame;

/**
 *
 * @author userr
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        hospitalName.setText(DocPanel.hospital+" Hospital");
        System.out.println(login.LoginPersonName+"   "+login.LoginPersonType);
        if(login.LoginPersonType.equals("Staff")){
            addpatient.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel7Exit1 = new javax.swing.JLabel();
        jLabel8Mini = new javax.swing.JLabel();
        back1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addpatient = new javax.swing.JButton();
        leaveNote = new javax.swing.JButton();
        viewpatient = new javax.swing.JButton();
        viewnote = new javax.swing.JButton();
        hospitalName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 290, 60));

        logout.setBackground(new java.awt.Color(102, 102, 102));
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log out");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 77, -1));

        jLabel7Exit1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7Exit1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7Exit1.setText("X");
        jLabel7Exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7Exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7Exit1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7Exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, -1, 36));

        jLabel8Mini.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8Mini.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8Mini.setText("-");
        jLabel8Mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8Mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MiniMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8Mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 20, 36));

        back1.setBackground(new java.awt.Color(102, 102, 102));
        back1.setForeground(new java.awt.Color(255, 255, 255));
        back1.setText("<<Back");
        back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        jPanel1.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanel2.setBackground(new java.awt.Color(231, 229, 229));

        addpatient.setBackground(new java.awt.Color(255, 255, 255));
        addpatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addpatient.setForeground(new java.awt.Color(102, 102, 102));
        addpatient.setText("Add New Patient");
        addpatient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpatientActionPerformed(evt);
            }
        });

        leaveNote.setBackground(new java.awt.Color(255, 255, 255));
        leaveNote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        leaveNote.setForeground(new java.awt.Color(102, 102, 102));
        leaveNote.setText("Leave Note");
        leaveNote.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leaveNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveNoteActionPerformed(evt);
            }
        });

        viewpatient.setBackground(new java.awt.Color(255, 255, 255));
        viewpatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewpatient.setForeground(new java.awt.Color(102, 102, 102));
        viewpatient.setText("View Current Patient");
        viewpatient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpatientActionPerformed(evt);
            }
        });

        viewnote.setBackground(new java.awt.Color(255, 255, 255));
        viewnote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewnote.setForeground(new java.awt.Color(102, 102, 102));
        viewnote.setText("View Note");
        viewnote.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewnoteActionPerformed(evt);
            }
        });

        hospitalName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hospitalName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalName.setText("HospitalName");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(leaveNote, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(viewpatient, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(addpatient, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(viewnote, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(hospitalName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(addpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(leaveNote, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewnote, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        //creating object of login form and set visible
        login w=new login();
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void addpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpatientActionPerformed
    AddPatient w=new AddPatient();
        w.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_addpatientActionPerformed

    private void jLabel7Exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7Exit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7Exit1MouseClicked

    private void jLabel8MiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MiniMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel8MiniMouseClicked

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
       DocPanel w=new DocPanel();
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back1ActionPerformed

    private void leaveNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveNoteActionPerformed
        // TODO add your handling code here:
        LeaveNote w=new LeaveNote();
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leaveNoteActionPerformed

    private void viewpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpatientActionPerformed
        // TODO add your handling code here:
        ViewPatient w=new ViewPatient();
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewpatientActionPerformed

    private void viewnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewnoteActionPerformed
        // TODO add your handling code here:
        ViewNote w=new ViewNote();
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewnoteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpatient;
    private javax.swing.JButton back1;
    private javax.swing.JLabel hospitalName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7Exit1;
    private javax.swing.JLabel jLabel8Mini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton leaveNote;
    private javax.swing.JButton logout;
    private javax.swing.JButton viewnote;
    private javax.swing.JButton viewpatient;
    // End of variables declaration//GEN-END:variables
}
